site_name: 赛凡链文档
nav:
    - 首页: index.md
    - 白皮书: whitebook.md
    - 用户手册: manual.md
    - 成为验证人: validator.md
    - 发展路线图: roadmap.md
    - 贡献文档: join.md
copyright: Copyright &copy; 2021 <a href="http://docs.scifanchain.com">赛凡链</a>.
# theme: readthedocs

theme:
  name: material

dev_addr: '127.0.0.1:9000'